name: qLDPC-decoding-gpu
channels:
  - nvidia
dependencies:
  - python=3.11
  - jupyterlab
  - numpy
  - matplotlib
  - numba
  - pandas
  - pytorch::pytorch=2.1.2=py3.11_cuda11.8_cudnn8.7.0_0
  - pytorch::pytorch-cuda=11.8
  - pytest
  - pip
  - pip:
    - galois
    - stim
    - ldpc
    - pymatching
    - livelossplot
